### ISSUE TITLE
No resource, method, or local variable named `home_basedir' for resource users_manage

### ISSUE THREAD

**Issue by matkam** [chef-cookbooks/users#407]
### Cookbook version
5.1.0

### Chef-client version
12.6.0

### Platform Details
Linux Ubuntu 14.04.2

### Scenario:
The "users_manage" resource can not reference the "home_basedir" library helper method:
```   ================================================================================
    Error executing action `create` on resource 'users_manage[sysadmin]'
    ================================================================================
    
    NameError
    ---------
    No resource, method, or local variable named `home_basedir' for `Custom resource users_manage from cookbook users action provider "sysadmin"'
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/users/resources/manage.rb:50:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/users/resources/manage.rb:36:in `block in class_from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/my_base/recipes/default.rb
    
     38: users_manage "sysadmin" do
     39:   group_id 2300
     40:   action [ :create ]
     41: end
     42: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/my_base/recipes/default.rb:38:in `from_file'
    
    users_manage("sysadmin") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :users_manage
      cookbook_name "voxel_base"
      recipe_name "default"
      group_id 2300
      group_name "sysadmin"
      data_bag "users"
      search_group "sysadmin"
    end
```

**Comment by matkam** [comment]
Never mind. Just noticed this cookbook is not supported chef-client pre 12.7.
